# Default configuration for the Fluid Simulation

particle_radius = 3.0
particle_count = 3000
boundary_damping = 0.7
mass = 1.0
smoothing_radius = 40.0 # Simulation cells are based on this
interaction_radius = 200.0

# Ghost particle settings
target_ghost_spacing = 3.0 # Multiplied by particle_radius for actual spacing in ghost cells
start_ghost_spacing_multiplier = 2.6 # How much denser particles are near the wall initially
ghost_wall_start_percent = 0.6 # How far up the side walls ghost particles start appearing (0.0=bottom, 1.0=top)

# These can be overridden by command-line arguments
fluid_type = "Liquid"  # Options: "Liquid", "Gas"
fluid_spawn_mode = "Grid" # Options: "Grid", "Flow"

# Flow mode specific settings (ignored if fluid_spawn_mode is not "Flow")
flow_spawn_rate = 100.0 # Particles per second
flow_spawn_width = 120.0 # Width of the spawn area for flow mode

# Configuration for Liquid type
[liquid]
gravity = { x = 0.0, y = 1.0 }
target_density = 5000.0
pressure_multiplier = 750.0
near_pressure_multiplier = 100.0
viscosity_strength = 3.0
interaction_strength = 2500.0

# Configuration for Gas type
[gas]
gravity = { x = 0.0, y = 0.0 }
target_density = 150.0
pressure_multiplier = 150.0
near_pressure_multiplier = 0.0
viscosity_strength = 5.0
interaction_strength = 5000.0
